# Generated by Django 4.2.25 on 2025-11-03 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('item_sold', 'Item Sold'), ('barter_request', 'Barter Request'), ('barter_accepted', 'Barter Accepted'), ('barter_rejected', 'Barter Rejected'), ('message_received', 'Message Received'), ('forum_reply', 'Forum Reply'), ('system_announcement', 'System Announcement'), ('wishlist_match', 'Wishlist Match')], max_length=30, unique=True)),
                ('title_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
                ('email_subject_template', models.CharField(blank=True, max_length=200)),
                ('email_body_template', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_order_updates', models.BooleanField(default=True)),
                ('email_payment_updates', models.BooleanField(default=True)),
                ('email_barter_updates', models.BooleanField(default=True)),
                ('email_messages', models.BooleanField(default=True)),
                ('email_forum_replies', models.BooleanField(default=True)),
                ('email_system_announcements', models.BooleanField(default=True)),
                ('push_order_updates', models.BooleanField(default=True)),
                ('push_payment_updates', models.BooleanField(default=True)),
                ('push_barter_updates', models.BooleanField(default=True)),
                ('push_messages', models.BooleanField(default=True)),
                ('push_forum_replies', models.BooleanField(default=True)),
                ('push_system_announcements', models.BooleanField(default=True)),
                ('in_app_order_updates', models.BooleanField(default=True)),
                ('in_app_payment_updates', models.BooleanField(default=True)),
                ('in_app_barter_updates', models.BooleanField(default=True)),
                ('in_app_messages', models.BooleanField(default=True)),
                ('in_app_forum_replies', models.BooleanField(default=True)),
                ('in_app_system_announcements', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_created', 'Order Created'), ('order_updated', 'Order Updated'), ('order_cancelled', 'Order Cancelled'), ('payment_received', 'Payment Received'), ('item_sold', 'Item Sold'), ('barter_request', 'Barter Request'), ('barter_accepted', 'Barter Accepted'), ('barter_rejected', 'Barter Rejected'), ('message_received', 'Message Received'), ('forum_reply', 'Forum Reply'), ('system_announcement', 'System Announcement'), ('wishlist_match', 'Wishlist Match')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('related_item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_order_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_barter_id', models.PositiveIntegerField(blank=True, null=True)),
                ('related_forum_post_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
