# Generated by Django 4.2.25 on 2025-11-11 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wanted', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wanteditem',
            name='is_free_post',
            field=models.BooleanField(default=False, help_text='Whether this post used a free posting credit'),
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount paid for posting this wanted item', max_digits=8),
        ),
    ]
