# Generated by Django 4.2.25 on 2025-11-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact information for buyers', max_length=50),
        ),
    ]
