# Generated by Django 4.2.25 on 2025-11-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_urls',
            field=models.JSONField(blank=True, default=list, help_text='Array of image URLs (base64 data URLs or external URLs)'),
        ),
        migrations.AlterField(
            model_name='item',
            name='image_url',
            field=models.URLField(blank=True, help_text='Deprecated: Use image_urls for multiple images', null=True),
        ),
    ]
