# Generated by Django 4.2.25 on 2025-11-03 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_item_image_urls_alter_item_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured items shown on featured page (requires membership)'),
        ),
    ]
