# Generated by Django 4.2.25 on 2025-11-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allow_barter',
            field=models.BooleanField(default=False, help_text='Item can be exchanged even if it has a price'),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_barter',
            field=models.BooleanField(default=False, help_text='Item is primarily for barter (no price)'),
        ),
    ]
